language: android
jdk:
  - oraclejdk8
    
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
 
before_install:
 - chmod +x gradlew
 
script:
  - ./gradlew clean build
